apiVersion: v1
entries:
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r30
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.15.0-debian-12-r44
        - name: postgresql
          image: docker.io/bitnami/postgresql:17.0.0-debian-12-r1
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 17.0.0
    created: "2024-10-06T14:25:21.6528829+07:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: ee12e8b33288078412b86b22163fac70dc1fbc758db123b0dfb79b0972d83ba5
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - charts/postgresql-16.0.1.tgz
    version: 16.0.1
  product-svc:
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2024-10-06T14:25:21.6579221+07:00"
    dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.0.1
    description: A Helm chart for product-svc
    digest: a38a7e80517ae0a355fb79912afb9327567cd2757e548382aa9309796f9dc5b9
    maintainers:
    - email: ngovuminhdat@gmail.com
      name: DatNvm
      url: github.com/ngodat0103
    name: product-svc
    type: application
    urls:
    - charts/product-svc-0.0.2.tgz
    version: 0.0.2
generated: "2024-10-06T14:25:21.6492422+07:00"
