apiVersion: 1
deleteDatasources:
  - name: Prometheus
  - name: Tempo
#  - name: Loki

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus-release-server.prometheus.svc.cluster.local:80
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo-release.grafana.svc.cluster.local:3100
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'
#  - name: Loki
#    type: loki
#    uid: loki
#    access: proxy
#    orgId: 1
#    editable: true
#    url: http://gateway:3100
#    jsonData:
#      httpHeaderName1: "X-Scope-OrgID"
#      derivedFields:
#        - datasourceUid: tempo
#          matcherRegex: "\\[.+,(.+),.+\\]"
#          name: TraceID
#          url: '$${__value.raw}'
    secureJsonData:
      httpHeaderValue1: "tenant1"